### ISSUE TITLE
transaltion: polish

### ISSUE THREAD

**Issue by ttr** [ds5678/Better-Fuel-Management#1]
"No containers with remaining capacity available" - not directly, but context based would be 'Brak zbiorników z wymaganą pojemnością'

"Drain" -> 'Opróżni' (empty it)

"Draining..." -> 'Opróznianie' (empting) / 'Przelewanie' (pouring liquid)  - second one might better if it's to another container.

"Lost" (a verb meaning wasted) - "Stracone/Stracony" (lost) or "Zniszczone/Zniszczona/Zniszczony" (destroyed) - they are gender-based, in terms of "lost(thrown away/wasted) fuel" as accidental or by-product it would be 'Stracone paliwo', or simply 'Stracone'

"Already empty" - if this is "X is already empty" in PL would be "X jest just pusty/-a" (gain gender based - can will be "pusta", container "pusty"), You could do this more generic, as "object is (already) empty" which will be 'Objekt jest już pusty', or "thing is (already) empty" that would be 'Przedmiot jest już pusty' (this one will be more neutral and natural)

"Already full" - very similar to above - full is 'pełny', so looking on last example, will be 'Przedmiot jest juz pełny'

The last two, in this situation, can be used as "tank is empty/full", then this will become 'Zbiornik jest już pusty/pełny'

If accents will be problematic, convert them to ascii/latin-1

**Comment by ds5678** [comment]
Sorry ttr. I didn't notice this until now. I'll make these changes in the next update.

**Comment by ds5678** [comment]
Your localizations have been implemented in the most recent update. Thanks ttr
