### ISSUE TITLE
Refueling Bug / Conflict?

### ISSUE THREAD

**Issue by KazTheMercenary** [ds5678/Better-Fuel-Management#2]
Hey guys, I can't tell if this is a bug, or a conflict.

(as an aside, please update your Readme.  Assetloader is no longer a step!)

When I go to refuel a lantern, I'm getting an odd style of fuel numbers, and a CTD if I attempt to refuel.
I haven't messed with any settings... do I need to?  And I thought I checked mods to make sure they weren't any conflicting.

Thoughts?

https://ibb.co/w7gLWcd

**Comment by ds5678** [comment]
This should be fixed in 65647fe
